### Endpoint de teste
Post http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Gabriel",
    "email": "gabriel@gmail.com",
    "password": "123456"
}

###

POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "gabriel@gmail.com",
    "password": "123456"
}

###

POST http://localhost:3003/shows/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzkwNTg1NDQsImV4cCI6MTY3OTE0NDk0NH0.BB4tFezLohrt6R3v0ZaYSAG0pBHwd5NmcttVwX7sOKs

{
    "banda": "Natiruts",
    "data": "07/12/2023"
}

###

POST http://localhost:3003/shows/ticket
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZkODI3ZTJmLTU4ODctNGI4NS05ZTg1LWUxYzE5MjQ2MzY5NSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzkwNzk0NDEsImV4cCI6MTY3OTE2NTg0MX0.flbIKytQ-Vvh-CGoAwS49FxfhtZFL2VaaD_uBHXA9KY

{
    "showId": "53631f56-decc-4f39-8112-f523f002965f",
    "userId": "fd827e2f-5887-4b85-9e85-e1c192463695"
}

###

DELETE http://localhost:3003/shows/53631f56-decc-4f39-8112-f523f002965f
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZkODI3ZTJmLTU4ODctNGI4NS05ZTg1LWUxYzE5MjQ2MzY5NSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzkwNzk0NDEsImV4cCI6MTY3OTE2NTg0MX0.flbIKytQ-Vvh-CGoAwS49FxfhtZFL2VaaD_uBHXA9KY

###

GET http://localhost:3003/shows/